/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Job
         * @description Paste a job description: it is parsed into requirements (cached per text).
         */
        post: operations["create_job_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/match": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Match
         * @description Check the profile against a parsed job: status and evidence per requirement.
         */
        post: operations["match_jobs__job_id__match_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/tailor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Tailor
         * @description Start tailoring a CV for a parsed job; it pauses when drafts are ready for review.
         */
        post: operations["start_tailor_jobs__job_id__tailor_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run
         * @description Where a run is, with its drafts once they are ready for review.
         */
        get: operations["get_run_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Review
         * @description Accept, edit or reject each draft. Edits are checked; a failing edit comes back.
         */
        post: operations["review_runs__run_id__review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/render": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Render Run
         * @description Compile the reviewed CV to PDF and run the ATS check on it.
         */
        post: operations["render_run_runs__run_id__render_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/cv.pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run Pdf */
        get: operations["run_pdf_runs__run_id__cv_pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/cv.tex": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run Tex */
        get: operations["run_tex_runs__run_id__cv_tex_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Run Events
         * @description Server-sent events: one per finished step, then the run's status.
         */
        get: operations["run_events_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CreateJob */
        CreateJob: {
            /**
             * Text
             * @description The job description, pasted as text
             */
            text: string;
            /** Company */
            company?: string | null;
            /** Url */
            url?: string | null;
        };
        /** DraftOut */
        DraftOut: {
            /** Source Id */
            source_id: string;
            /** Entry Id */
            entry_id: string;
            /** Original */
            original: string;
            /** Text */
            text: string;
            /** Attempts */
            attempts: number;
            /** Issues */
            issues: string[];
            /** History */
            history: unknown[][];
            /** Passed */
            passed: boolean;
            /** Fallback */
            fallback: boolean;
            /**
             * User Edited
             * @default false
             */
            user_edited: boolean;
            /**
             * User Rejected
             * @default false
             */
            user_rejected: boolean;
        };
        /** ErrorOut */
        ErrorOut: {
            /** Detail */
            detail: string;
            /**
             * Issues
             * @default []
             */
            issues: string[];
        };
        /** Evidence */
        Evidence: {
            /** Id */
            id: string;
            /** Where */
            where: string;
            /** Text */
            text: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobDescription */
        JobDescription: {
            /** Title */
            title: string;
            /** Company */
            company: string | null;
            /**
             * Seniority
             * @enum {string}
             */
            seniority: "intern" | "fresher" | "junior" | "mid" | "senior" | "unknown";
            /**
             * Language
             * @enum {string}
             */
            language: "vi" | "en";
            /** Location */
            location: string | null;
            /** Must Have */
            must_have: components["schemas"]["Requirement"][];
            /** Nice To Have */
            nice_to_have: components["schemas"]["Requirement"][];
            /** Responsibilities */
            responsibilities: string[];
            /** Keywords */
            keywords: string[];
        };
        /** JobOut */
        JobOut: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Company */
            company: string | null;
            /** Cached */
            cached: boolean;
            jd: components["schemas"]["JobDescription"];
        };
        /** MatchOut */
        MatchOut: {
            /** Job Id */
            job_id: number;
            /** Score */
            score: number;
            /** Level */
            level: ("intern" | "fresher" | "junior" | "mid" | "senior" | "unknown") | null;
            /** Profile Version */
            profile_version: string;
            /** Cached */
            cached: boolean;
            /** Requirements */
            requirements: components["schemas"]["RequirementOut"][];
            /** Excluded */
            excluded: string[];
        };
        /** MatchRequest */
        MatchRequest: {
            /**
             * Level
             * @description Applicant level for postings that hire several; default: lowest accepted
             */
            level?: ("intern" | "fresher" | "junior" | "mid" | "senior" | "unknown") | null;
        };
        /** RenderOut */
        RenderOut: {
            /** Run Id */
            run_id: string;
            /** Pages */
            pages: number;
            /** Ats Ok */
            ats_ok: boolean;
            /** Issues */
            issues: string[];
            /** Warnings */
            warnings: string[];
            /** Pdf Url */
            pdf_url: string;
            /** Tex Url */
            tex_url: string;
        };
        /** RenderRequest */
        RenderRequest: {
            /** Keywords */
            keywords?: string[] | null;
        };
        /** Requirement */
        Requirement: {
            /** Id */
            id: string;
            /** Text */
            text: string;
            /**
             * Category
             * @enum {string}
             */
            category: "skill" | "experience" | "education" | "language" | "soft_skill" | "other";
            /** Any Of */
            any_of: string[];
            /** Level */
            level: ("intern" | "fresher" | "junior" | "mid" | "senior" | "unknown") | null;
        };
        /** RequirementOut */
        RequirementOut: {
            /** Id */
            id: string;
            /** Text */
            text: string;
            /**
             * Bucket
             * @enum {string}
             */
            bucket: "must" | "nice";
            /**
             * Category
             * @enum {string}
             */
            category: "skill" | "experience" | "education" | "language" | "soft_skill" | "other";
            /** Any Of */
            any_of: string[];
            /**
             * Status
             * @enum {string}
             */
            status: "met" | "partial" | "missing" | "unverifiable";
            /** Note */
            note: string;
            /** Evidence */
            evidence: components["schemas"]["Evidence"][];
        };
        /** ReviewDecisionIn */
        ReviewDecisionIn: {
            /** Source Id */
            source_id: string;
            /**
             * Action
             * @enum {string}
             */
            action: "accept" | "edit" | "reject";
            /** Text */
            text?: string | null;
        };
        /** ReviewRequest */
        ReviewRequest: {
            /**
             * Decisions
             * @default []
             */
            decisions: components["schemas"]["ReviewDecisionIn"][];
        };
        /** RunOut */
        RunOut: {
            /** Run Id */
            run_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "waiting_review" | "done" | "error" | "not_found";
        };
        /** RunStatusOut */
        RunStatusOut: {
            /** Run Id */
            run_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "waiting_review" | "done" | "error" | "not_found";
            /**
             * Drafts
             * @default []
             */
            drafts: components["schemas"]["DraftOut"][];
            /**
             * Review Errors
             * @default {}
             */
            review_errors: {
                [key: string]: string[];
            };
            /** Cv */
            cv?: {
                [key: string]: unknown;
            } | null;
            /** Error */
            error?: string | null;
        };
        /** TailorRequest */
        TailorRequest: {
            /** Level */
            level?: ("intern" | "fresher" | "junior" | "mid" | "senior" | "unknown") | null;
            /**
             * Use Judge
             * @default true
             */
            use_judge: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    create_job_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateJob"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    get_job_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    match_jobs__job_id__match_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["MatchRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    start_tailor_jobs__job_id__tailor_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["TailorRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    get_run_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunStatusOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_runs__run_id__review_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunStatusOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    render_run_runs__run_id__render_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RenderRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RenderOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    run_pdf_runs__run_id__cv_pdf_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_tex_runs__run_id__cv_tex_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_events_runs__run_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
