/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Job
         * @description Paste a job description: it is parsed into requirements (cached per text).
         */
        post: operations["create_job_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/match": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Match
         * @description Check the profile against a parsed job: status and evidence per requirement.
         */
        post: operations["match_jobs__job_id__match_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CreateJob */
        CreateJob: {
            /**
             * Text
             * @description The job description, pasted as text
             */
            text: string;
            /** Company */
            company?: string | null;
            /** Url */
            url?: string | null;
        };
        /** ErrorOut */
        ErrorOut: {
            /** Detail */
            detail: string;
            /**
             * Issues
             * @default []
             */
            issues: string[];
        };
        /** Evidence */
        Evidence: {
            /** Id */
            id: string;
            /** Where */
            where: string;
            /** Text */
            text: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobDescription */
        JobDescription: {
            /** Title */
            title: string;
            /** Company */
            company: string | null;
            /**
             * Seniority
             * @enum {string}
             */
            seniority: "intern" | "fresher" | "junior" | "mid" | "senior" | "unknown";
            /**
             * Language
             * @enum {string}
             */
            language: "vi" | "en";
            /** Location */
            location: string | null;
            /** Must Have */
            must_have: components["schemas"]["Requirement"][];
            /** Nice To Have */
            nice_to_have: components["schemas"]["Requirement"][];
            /** Responsibilities */
            responsibilities: string[];
            /** Keywords */
            keywords: string[];
        };
        /** JobOut */
        JobOut: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Company */
            company: string | null;
            /** Cached */
            cached: boolean;
            jd: components["schemas"]["JobDescription"];
        };
        /** MatchOut */
        MatchOut: {
            /** Job Id */
            job_id: number;
            /** Score */
            score: number;
            /** Level */
            level: ("intern" | "fresher" | "junior" | "mid" | "senior" | "unknown") | null;
            /** Profile Version */
            profile_version: string;
            /** Cached */
            cached: boolean;
            /** Requirements */
            requirements: components["schemas"]["RequirementOut"][];
            /** Excluded */
            excluded: string[];
        };
        /** MatchRequest */
        MatchRequest: {
            /**
             * Level
             * @description Applicant level for postings that hire several; default: lowest accepted
             */
            level?: ("intern" | "fresher" | "junior" | "mid" | "senior" | "unknown") | null;
        };
        /** Requirement */
        Requirement: {
            /** Id */
            id: string;
            /** Text */
            text: string;
            /**
             * Category
             * @enum {string}
             */
            category: "skill" | "experience" | "education" | "language" | "soft_skill" | "other";
            /** Any Of */
            any_of: string[];
            /** Level */
            level: ("intern" | "fresher" | "junior" | "mid" | "senior" | "unknown") | null;
        };
        /** RequirementOut */
        RequirementOut: {
            /** Id */
            id: string;
            /** Text */
            text: string;
            /**
             * Bucket
             * @enum {string}
             */
            bucket: "must" | "nice";
            /**
             * Category
             * @enum {string}
             */
            category: "skill" | "experience" | "education" | "language" | "soft_skill" | "other";
            /** Any Of */
            any_of: string[];
            /**
             * Status
             * @enum {string}
             */
            status: "met" | "partial" | "missing" | "unverifiable";
            /** Note */
            note: string;
            /** Evidence */
            evidence: components["schemas"]["Evidence"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    create_job_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateJob"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    get_job_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    match_jobs__job_id__match_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["MatchRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
}
